production:
  adapter: mysql2
  encoding: utf8
  database: store
  username: root
  password: 
  host: localhost
  reconnect: true
  port: 3306

development:
  adapter: mysql2
  encoding: utf8
  database: store
  username: root
  password: 
  host: localhost
  reconnect: true
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: store-test
  username: root
  password: 
  host: localhost
  reconnect: true
  port: 3306
