# Admin site login
admin_username: "admin"
admin_password: "password"

# Presentation stuf
company_name: "My Company"
company_url: "http://www.mycompany.com/"
company_logo_path: ""
store_name: "My Company Store"
copyright_html: "Copyright &copy; 2011 My Company. All rights reserved."
google_analytics_account: ""
include_mint: false
paypal_express_checkout_header_image: "https://www.mycompany.com/images/mylogo.png"

# Payment types?
allow_google_checkout: false
allow_creditcards: false
allow_paypal_express: false

# Supported payment types (One or more of: gcheckout, paypal_express_checkout, paypal_wps, creditcard)
payment_types: ["paypal_wps"]
default_payment_type: "paypal_wps"

# Currency settings
# Currency in which to display reports in admin section
report_currency:
  code:        USD
  precision:  2
  unit:       "$"
  separator:  "."
  delimiter:  ","
  format:     "%u%n"

# Default currency for sales
default_currency: 
  code:        USD

# Email settings
support_email: "support@mycompany.com"
sales_email: "sales@mycompany.com"

purchase_receipt_sender_email: "My Company <info@mycompany.com>"
purchase_receipt_bcc_email: "orders@mycompany.com"

send_lost_license_sent_notification_email: false
lost_license_sent_notification_sender_email: "My Company <support@mycompany.com>"
lost_license_sent_notification_recipient_email: "info@mycompany.com"

crash_report_sender_email: "bugs@mycompany.com"
crash_report_recipient_email: "bugs@mycompany.com"

# Using SSL?
#
# Turning this on redirects most requests that come in through http to https
# In addition, if you're using Apache, you might need to add the following
# to its SSL configuration:
#
#		RequestHeader set X_FORWARDED_PROTO 'https'
#
redirect_to_ssl: true
